"""add_agent_workflows_table

Revision ID: 1f73bd15b1c0
Revises: 63a1fb41b4bb
Create Date: 2026-01-03 15:31:57.608083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f73bd15b1c0'
down_revision: Union[str, None] = '63a1fb41b4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_workflows',
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Associated agent ID'),
    sa.Column('workflow_id', sa.String(length=36), nullable=False, comment='Workflow ID (UUID string) - references external workflow service'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this workflow is enabled for the agent'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_agent_workflows')
    # ### end Alembic commands ###
