"""init

Revision ID: 66112c4c8880
Revises: 
Create Date: 2025-12-02 06:17:47.539917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66112c4c8880'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_tool_associations',
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Associated agent ID'),
    sa.Column('tool_id', sa.UUID(), nullable=False, comment='Associated tool ID'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether tool is enabled for this agent'),
    sa.Column('permissions', sa.JSON(), nullable=True, comment='Tool permissions array'),
    sa.Column('config', sa.JSON(), nullable=True, comment='Agent-specific tool configuration overrides'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_tool_assoc_agent_id', 'ai_agent_tool_associations', ['agent_id'], unique=False)
    op.create_index('idx_agent_tool_assoc_tool_id', 'ai_agent_tool_associations', ['tool_id'], unique=False)
    op.create_table('ai_collections',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Associated project ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Collection display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional collection description'),
    sa.Column('external_id', sa.String(length=64), nullable=False, comment='External RAG service collection identifier'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('ai_llm_providers',
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID (externally provided)'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Associated project ID'),
    sa.Column('alias', sa.String(length=80), nullable=False, comment='Unique alias within project'),
    sa.Column('provider_kind', sa.String(length=40), nullable=False, comment='Provider kind: openai/anthropic/google/openai_compatible'),
    sa.Column('vendor', sa.String(length=40), nullable=True, comment='Vendor label (e.g. deepseek)'),
    sa.Column('api_base_url', sa.String(length=255), nullable=True, comment='Custom API base URL'),
    sa.Column('api_key', sa.String(length=255), nullable=True, comment='API key (do NOT log)'),
    sa.Column('organization', sa.String(length=100), nullable=True, comment='Organization/tenant id'),
    sa.Column('timeout', sa.Float(), nullable=True, comment='Request timeout seconds'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this provider is active'),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was last synchronized'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'alias', name='uq_ai_llm_providers_project_alias')
    )
    op.create_table('ai_project_ai_configs',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Project UUID (primary key)'),
    sa.Column('default_chat_provider_id', sa.UUID(), nullable=True, comment='LLM provider id for default chat model'),
    sa.Column('default_chat_model', sa.String(length=150), nullable=True, comment="Default chat model name (e.g., 'gpt-4o')"),
    sa.Column('default_embedding_provider_id', sa.UUID(), nullable=True, comment='LLM provider id for default embedding model'),
    sa.Column('default_embedding_model', sa.String(length=150), nullable=True, comment='Default embedding model name'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of last successful sync to RAG'),
    sa.Column('sync_status', sa.String(length=32), nullable=True, comment='Current sync status: pending|success|failed|not_synced'),
    sa.Column('sync_error', sa.Text(), nullable=True, comment='Last sync error message, if any'),
    sa.Column('sync_attempt_count', sa.Integer(), nullable=True, comment='Number of sync attempts for current config'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('ai_projects',
    sa.Column('id', sa.UUID(), nullable=False, comment='Project UUID synchronized from API service'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Project name'),
    sa.Column('api_key', sa.String(length=255), nullable=False, comment='API key for authentication'),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this record was last synchronized'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('ai_tools',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Associated project ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Tool name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional tool description'),
    sa.Column('tool_type', sa.Enum('MCP', 'FUNCTION', name='tool_type_enum'), nullable=False, comment='Tool type (MCP or FUNCTION)'),
    sa.Column('transport_type', sa.String(length=50), nullable=True, comment='Transport type (e.g., http, stdio, sse)'),
    sa.Column('endpoint', sa.String(length=1024), nullable=True, comment='Endpoint URL or path'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True, comment='Tool configuration as JSON object'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tools_name', 'ai_tools', ['name'], unique=False)
    op.create_index('idx_tools_project_id', 'ai_tools', ['project_id'], unique=False)
    op.create_table('ai_teams',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Associated project ID (logical reference to API service)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Team name'),
    sa.Column('model', sa.String(length=150), nullable=True, comment='LLM model used by the team in format "provider:model_name"'),
    sa.Column('instruction', sa.Text(), nullable=True, comment='Team system prompt/instructions'),
    sa.Column('expected_output', sa.Text(), nullable=True, comment='Expected output format description'),
    sa.Column('session_id', sa.String(length=150), nullable=True, comment='Team session identifier'),
    sa.Column('llm_provider_id', sa.UUID(), nullable=True, comment='Associated LLM provider (credentials) ID'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this is the default team for the project'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.ForeignKeyConstraint(['llm_provider_id'], ['ai_llm_providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'is_default', name='uq_ai_teams_default_per_project')
    )
    op.create_table('ai_agents',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Associated project ID (logical reference to API service)'),
    sa.Column('team_id', sa.UUID(), nullable=True, comment='Associated team ID for team-based organization'),
    sa.Column('llm_provider_id', sa.UUID(), nullable=True, comment='Associated LLM provider (credentials) ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Agent name'),
    sa.Column('instruction', sa.Text(), nullable=True, comment='Agent system instruction'),
    sa.Column('model', sa.String(length=150), nullable=False, comment='LLM model with provider prefix (format: "provider:model_name")'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this is the default agent for the project'),
    sa.Column('config', sa.JSON(), nullable=True, comment='Agent configuration (temperature, max_tokens, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.ForeignKeyConstraint(['llm_provider_id'], ['ai_llm_providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['ai_teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_agent_collections',
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Associated agent ID'),
    sa.Column('collection_id', sa.String(length=36), nullable=False, comment='Collection ID (UUID string) - references external RAG service'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this collection is enabled for the agent'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_agent_usage_records',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Associated project ID (logical reference to API service)'),
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Agent being tracked'),
    sa.Column('request_count', sa.Integer(), nullable=False, comment='Total number of requests made by the agent'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='Number of successful requests'),
    sa.Column('failure_count', sa.Integer(), nullable=False, comment='Number of failed requests'),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=True, comment='Average response time in milliseconds'),
    sa.Column('last_request_time', sa.DateTime(timezone=True), nullable=True, comment='Most recent request timestamp'),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False, comment='Start of the tracking period'),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False, comment='End of the tracking period'),
    sa.Column('aggregation_type', sa.String(length=20), nullable=False, comment='Type of aggregation: hourly, daily, weekly, monthly'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_collection_usage_records',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Associated project ID (logical reference to API service)'),
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Agent that accessed the collection'),
    sa.Column('collection_id', sa.String(length=36), nullable=False, comment='Collection ID (UUID string) - references external RAG service'),
    sa.Column('session_id', sa.String(length=255), nullable=True, comment='Session or conversation identifier'),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='User or visitor identifier who triggered the query'),
    sa.Column('query_text', sa.Text(), nullable=True, comment='Search query or prompt text'),
    sa.Column('query_type', sa.String(length=50), nullable=False, comment='Type of query: semantic_search, keyword_search, hybrid'),
    sa.Column('query_parameters', sa.JSON(), nullable=True, comment='Query parameters (filters, limits, etc.) in JSON format'),
    sa.Column('documents_retrieved', sa.Integer(), nullable=False, comment='Number of document chunks retrieved'),
    sa.Column('retrieved_documents', sa.JSON(), nullable=True, comment='Retrieved document chunks with metadata and scores'),
    sa.Column('max_relevance_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='Highest relevance score from retrieved documents'),
    sa.Column('avg_relevance_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='Average relevance score from retrieved documents'),
    sa.Column('query_duration_ms', sa.Integer(), nullable=True, comment='Query execution duration in milliseconds'),
    sa.Column('query_status', sa.String(length=20), nullable=False, comment='Query status: pending, success, error, timeout'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if query failed'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='When query execution started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When query execution completed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_tool_usage_records',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Associated project ID (logical reference to API service)'),
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Agent that used the tool'),
    sa.Column('tool_name', sa.String(length=355), nullable=False, comment='Tool name with provider prefix (format: "tool_provider:tool_name")'),
    sa.Column('session_id', sa.String(length=255), nullable=True, comment='Session or conversation identifier'),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='User or visitor identifier who triggered the tool usage'),
    sa.Column('input_parameters', sa.JSON(), nullable=True, comment='Parameters passed to the tool (JSON format)'),
    sa.Column('execution_result', sa.JSON(), nullable=True, comment='Result returned by the tool (JSON format)'),
    sa.Column('execution_status', sa.String(length=20), nullable=False, comment='Execution status: pending, success, error, timeout'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if execution failed'),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True, comment='Tool execution duration in milliseconds'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='When tool execution started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When tool execution completed'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp'),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_tool_usage_records')
    op.drop_table('ai_collection_usage_records')
    op.drop_table('ai_agent_usage_records')
    op.drop_table('ai_agent_collections')
    op.drop_table('ai_agents')
    op.drop_table('ai_teams')
    op.drop_index('idx_tools_project_id', table_name='ai_tools')
    op.drop_index('idx_tools_name', table_name='ai_tools')
    op.drop_table('ai_tools')
    op.drop_table('ai_projects')
    op.drop_table('ai_project_ai_configs')
    op.drop_table('ai_llm_providers')
    op.drop_table('ai_collections')
    op.drop_index('idx_agent_tool_assoc_tool_id', table_name='ai_agent_tool_associations')
    op.drop_index('idx_agent_tool_assoc_agent_id', table_name='ai_agent_tool_associations')
    op.drop_table('ai_agent_tool_associations')
    # ### end Alembic commands ###