"""init

Revision ID: 21097dc45146
Revises: 
Create Date: 2025-12-02 06:20:04.635560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision = '21097dc45146'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Ensure pgvector extension is available for Vector(...) columns
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    op.create_table('rag_collections',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('collection_type', sa.Enum('file', 'website', 'qa', name='collection_type_enum'), server_default='file', nullable=False),
    sa.Column('crawl_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collection_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_collections_collection_type', 'rag_collections', ['collection_type'], unique=False)
    op.create_index('idx_rag_collections_created_at', 'rag_collections', ['created_at'], unique=False)
    op.create_index('idx_rag_collections_deleted_at', 'rag_collections', ['deleted_at'], unique=False)
    op.create_index('idx_rag_collections_display_name', 'rag_collections', ['display_name'], unique=False)
    op.create_index('idx_rag_collections_project_display_name', 'rag_collections', ['project_id', 'display_name'], unique=False)
    op.create_index('idx_rag_collections_project_id', 'rag_collections', ['project_id'], unique=False)
    op.create_index('idx_rag_collections_tags', 'rag_collections', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('rag_embedding_configs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_embedding_configs_is_active', 'rag_embedding_configs', ['is_active'], unique=False)
    op.create_index('ix_rag_embedding_configs_project_id', 'rag_embedding_configs', ['project_id'], unique=False)
    op.create_index('uq_rag_embedding_configs_project_active', 'rag_embedding_configs', ['project_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('rag_projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_index('idx_rag_projects_api_key', 'rag_projects', ['api_key'], unique=False)
    op.create_index('idx_rag_projects_deleted_at', 'rag_projects', ['deleted_at'], unique=False)
    op.create_table('rag_files',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('storage_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['rag_collections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_files_collection_id', 'rag_files', ['collection_id'], unique=False)
    op.create_index('idx_rag_files_content_type', 'rag_files', ['content_type'], unique=False)
    op.create_index('idx_rag_files_created_at', 'rag_files', ['created_at'], unique=False)
    op.create_index('idx_rag_files_deleted_at', 'rag_files', ['deleted_at'], unique=False)
    op.create_index('idx_rag_files_language', 'rag_files', ['language'], unique=False)
    op.create_index('idx_rag_files_project_content_type', 'rag_files', ['project_id', 'content_type'], unique=False)
    op.create_index('idx_rag_files_project_id', 'rag_files', ['project_id'], unique=False)
    op.create_index('idx_rag_files_project_status', 'rag_files', ['project_id', 'status'], unique=False)
    op.create_index('idx_rag_files_project_uploaded_by', 'rag_files', ['project_id', 'uploaded_by'], unique=False)
    op.create_index('idx_rag_files_status', 'rag_files', ['status'], unique=False)
    op.create_index('idx_rag_files_storage_provider', 'rag_files', ['storage_provider'], unique=False)
    op.create_index('idx_rag_files_tags', 'rag_files', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_rag_files_uploaded_by', 'rag_files', ['uploaded_by'], unique=False)
    op.create_table('rag_file_documents',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('document_title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['rag_collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['rag_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_file_documents_chunk_index', 'rag_file_documents', ['chunk_index'], unique=False)
    op.create_index('idx_rag_file_documents_collection_id', 'rag_file_documents', ['collection_id'], unique=False)
    op.create_index('idx_rag_file_documents_confidence_score', 'rag_file_documents', ['confidence_score'], unique=False)
    op.create_index('idx_rag_file_documents_content_tsv', 'rag_file_documents', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('idx_rag_file_documents_content_type', 'rag_file_documents', ['content_type'], unique=False)
    op.create_index('idx_rag_file_documents_created_at', 'rag_file_documents', ['created_at'], unique=False)
    op.create_index('idx_rag_file_documents_embedding_model', 'rag_file_documents', ['embedding_model'], unique=False)
    op.create_index('idx_rag_file_documents_file_chunk', 'rag_file_documents', ['file_id', 'chunk_index'], unique=False)
    op.create_index('idx_rag_file_documents_file_id', 'rag_file_documents', ['file_id'], unique=False)
    op.create_index('idx_rag_file_documents_language', 'rag_file_documents', ['language'], unique=False)
    op.create_index('idx_rag_file_documents_page_number', 'rag_file_documents', ['page_number'], unique=False)
    op.create_index('idx_rag_file_documents_token_count', 'rag_file_documents', ['token_count'], unique=False)
    op.create_table('rag_website_pages',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('parent_page_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('crawl_source', sa.String(length=64), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('discovered_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crawl_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('page_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['rag_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['rag_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_page_id'], ['rag_website_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_website_pages_collection_id', 'rag_website_pages', ['collection_id'], unique=False)
    op.create_index('idx_website_pages_collection_url', 'rag_website_pages', ['collection_id', 'url_hash'], unique=True)
    op.create_index('idx_website_pages_crawl_source', 'rag_website_pages', ['crawl_source'], unique=False)
    op.create_index('idx_website_pages_created_at', 'rag_website_pages', ['created_at'], unique=False)
    op.create_index('idx_website_pages_depth', 'rag_website_pages', ['depth'], unique=False)
    op.create_index('idx_website_pages_file_id', 'rag_website_pages', ['file_id'], unique=False)
    op.create_index('idx_website_pages_parent_page_id', 'rag_website_pages', ['parent_page_id'], unique=False)
    op.create_index('idx_website_pages_project_id', 'rag_website_pages', ['project_id'], unique=False)
    op.create_index('idx_website_pages_status', 'rag_website_pages', ['status'], unique=False)
    op.create_index('idx_website_pages_url_hash', 'rag_website_pages', ['url_hash'], unique=False)
    op.create_table('rag_qa_pairs',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('subcategory', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('qa_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['rag_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['rag_file_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qa_pairs_category', 'rag_qa_pairs', ['category'], unique=False)
    op.create_index('idx_qa_pairs_collection_id', 'rag_qa_pairs', ['collection_id'], unique=False)
    op.create_index('idx_qa_pairs_collection_question', 'rag_qa_pairs', ['collection_id', 'question_hash'], unique=True)
    op.create_index('idx_qa_pairs_created_at', 'rag_qa_pairs', ['created_at'], unique=False)
    op.create_index('idx_qa_pairs_deleted_at', 'rag_qa_pairs', ['deleted_at'], unique=False)
    op.create_index('idx_qa_pairs_project_id', 'rag_qa_pairs', ['project_id'], unique=False)
    op.create_index('idx_qa_pairs_question_hash', 'rag_qa_pairs', ['question_hash'], unique=False)
    op.create_index('idx_qa_pairs_source_type', 'rag_qa_pairs', ['source_type'], unique=False)
    op.create_index('idx_qa_pairs_status', 'rag_qa_pairs', ['status'], unique=False)
    op.create_index('idx_qa_pairs_tags', 'rag_qa_pairs', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_qa_pairs_tags', table_name='rag_qa_pairs', postgresql_using='gin')
    op.drop_index('idx_qa_pairs_status', table_name='rag_qa_pairs')
    op.drop_index('idx_qa_pairs_source_type', table_name='rag_qa_pairs')
    op.drop_index('idx_qa_pairs_question_hash', table_name='rag_qa_pairs')
    op.drop_index('idx_qa_pairs_project_id', table_name='rag_qa_pairs')
    op.drop_index('idx_qa_pairs_deleted_at', table_name='rag_qa_pairs')
    op.drop_index('idx_qa_pairs_created_at', table_name='rag_qa_pairs')
    op.drop_index('idx_qa_pairs_collection_question', table_name='rag_qa_pairs')
    op.drop_index('idx_qa_pairs_collection_id', table_name='rag_qa_pairs')
    op.drop_index('idx_qa_pairs_category', table_name='rag_qa_pairs')
    op.drop_table('rag_qa_pairs')
    op.drop_index('idx_website_pages_url_hash', table_name='rag_website_pages')
    op.drop_index('idx_website_pages_status', table_name='rag_website_pages')
    op.drop_index('idx_website_pages_project_id', table_name='rag_website_pages')
    op.drop_index('idx_website_pages_parent_page_id', table_name='rag_website_pages')
    op.drop_index('idx_website_pages_file_id', table_name='rag_website_pages')
    op.drop_index('idx_website_pages_depth', table_name='rag_website_pages')
    op.drop_index('idx_website_pages_created_at', table_name='rag_website_pages')
    op.drop_index('idx_website_pages_crawl_source', table_name='rag_website_pages')
    op.drop_index('idx_website_pages_collection_url', table_name='rag_website_pages')
    op.drop_index('idx_website_pages_collection_id', table_name='rag_website_pages')
    op.drop_table('rag_website_pages')
    op.drop_index('idx_rag_file_documents_token_count', table_name='rag_file_documents')
    op.drop_index('idx_rag_file_documents_page_number', table_name='rag_file_documents')
    op.drop_index('idx_rag_file_documents_language', table_name='rag_file_documents')
    op.drop_index('idx_rag_file_documents_file_id', table_name='rag_file_documents')
    op.drop_index('idx_rag_file_documents_file_chunk', table_name='rag_file_documents')
    op.drop_index('idx_rag_file_documents_embedding_model', table_name='rag_file_documents')
    op.drop_index('idx_rag_file_documents_created_at', table_name='rag_file_documents')
    op.drop_index('idx_rag_file_documents_content_type', table_name='rag_file_documents')
    op.drop_index('idx_rag_file_documents_content_tsv', table_name='rag_file_documents', postgresql_using='gin')
    op.drop_index('idx_rag_file_documents_confidence_score', table_name='rag_file_documents')
    op.drop_index('idx_rag_file_documents_collection_id', table_name='rag_file_documents')
    op.drop_index('idx_rag_file_documents_chunk_index', table_name='rag_file_documents')
    op.drop_table('rag_file_documents')
    op.drop_index('idx_rag_files_uploaded_by', table_name='rag_files')
    op.drop_index('idx_rag_files_tags', table_name='rag_files', postgresql_using='gin')
    op.drop_index('idx_rag_files_storage_provider', table_name='rag_files')
    op.drop_index('idx_rag_files_status', table_name='rag_files')
    op.drop_index('idx_rag_files_project_uploaded_by', table_name='rag_files')
    op.drop_index('idx_rag_files_project_status', table_name='rag_files')
    op.drop_index('idx_rag_files_project_id', table_name='rag_files')
    op.drop_index('idx_rag_files_project_content_type', table_name='rag_files')
    op.drop_index('idx_rag_files_language', table_name='rag_files')
    op.drop_index('idx_rag_files_deleted_at', table_name='rag_files')
    op.drop_index('idx_rag_files_created_at', table_name='rag_files')
    op.drop_index('idx_rag_files_content_type', table_name='rag_files')
    op.drop_index('idx_rag_files_collection_id', table_name='rag_files')
    op.drop_table('rag_files')
    op.drop_index('idx_rag_projects_deleted_at', table_name='rag_projects')
    op.drop_index('idx_rag_projects_api_key', table_name='rag_projects')
    op.drop_table('rag_projects')
    op.drop_index('uq_rag_embedding_configs_project_active', table_name='rag_embedding_configs', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_rag_embedding_configs_project_id', table_name='rag_embedding_configs')
    op.drop_index('ix_rag_embedding_configs_is_active', table_name='rag_embedding_configs')
    op.drop_table('rag_embedding_configs')
    op.drop_index('idx_rag_collections_tags', table_name='rag_collections', postgresql_using='gin')
    op.drop_index('idx_rag_collections_project_id', table_name='rag_collections')
    op.drop_index('idx_rag_collections_project_display_name', table_name='rag_collections')
    op.drop_index('idx_rag_collections_display_name', table_name='rag_collections')
    op.drop_index('idx_rag_collections_deleted_at', table_name='rag_collections')
    op.drop_index('idx_rag_collections_created_at', table_name='rag_collections')
    op.drop_index('idx_rag_collections_collection_type', table_name='rag_collections')
    op.drop_table('rag_collections')
    # ### end Alembic commands ###